services:
  puppeteer:
    build: .
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  node_modules:
